pipeline {
    agent any
    
    environment {
        // This matches the server ID from your generator
        JIRA_INSTANCE = 'CLOUD-12609af9-33fc-4f76-b34c-20e5e3190ea4'
        TEST_EXEC_KEY = 'LOGI-70'
    }

    stages {
        stage('Install Environment') {
            steps {
                // Ensures Python 3.14 is used to install pytest
                bat 'python -m pip install pytest'
            }
        }

        stage('Run Logic Tests') {
            steps {
                // Generates results.xml and prevents pipeline from stopping on test failure
                bat 'python -m pytest test_logic.py --junitxml=results.xml || exit 0'
            }
        }

        stage('Update Xray Execution') {
            steps {
                // The exact code generated by your Jenkins instance
                step([$class: 'XrayImportBuilder', 
                    endpointName: '/junit', 
                    importFilePath: 'results.xml', 
                    importInParallel: 'false', 
                    importToSameExecution: 'false', 
                    serverInstance: "${env.JIRA_INSTANCE}", 
                    testExecKey: "${env.TEST_EXEC_KEY}"
                ])
            }
        }
    }
}

